### ISSUE TITLE
Your code doesn't work in mine

### ISSUE THREAD

**Issue by mrardyan** [SilvVF/SupabaseRealtimeChatSwift#1]
I am currently working on a chat project using supabase-swift's Realtime. I have used your code and attempted to run it on my computer, but it is not working. I have created a "messages" table with the all necessary columns, and the data insertion process is successful. Database replication to that table already sets to realtime function. However, the channel subscription process is not working. Is there something that I am missing?

**Comment by SilvVF** [comment]
> I am currently working on a chat project using supabase-swift's Realtime. I have used your code and attempted to run it on my computer, but it is not working. I have created a "messages" table with the all necessary columns, and the data insertion process is successful. Database replication to that table already sets to realtime function. However, the channel subscription process is not working. Is there something that I am missing?

Hello, 

sorry for responding late haven't been on GitHub in a while I think you may have to enable RLS on the Messages table for the Realtime to work. It looks like queries on the table will return an empty array if this is not enabled.
![image](https://user-images.githubusercontent.com/98186105/231339868-cee9eb26-66e9-4873-8efa-893969d242ae.png)
![image](https://user-images.githubusercontent.com/98186105/231340585-7471ecc5-89a9-457f-a05f-90ad15e8aac7.png)

**Comment by SilvVF** [comment]
also in one part I use the API key from and url from a Bundle that wont be there from cloning the github code. The url and key would be whatever is in (from supabase website) project settings > API > Project URL for url and key would be Project API keys > the one with tags anon and public.


In ChatService class
`  convenience init() {
        var nsDictionary: NSDictionary?
        if let path = Bundle.main.path(forResource: "keys", ofType: "plist") {
           nsDictionary = NSDictionary(contentsOfFile: path)
        }
        let url = nsDictionary!["url"]! as! String
        let key = nsDictionary!["apikey"]! as! String
        self.init(urlString: url, key: key)
    }`

**Comment by AsifSyeed** [comment]
I am facing a similar issue for RLS. While the RLS is enabled, my realtimeClient doesn't trigger for insert, update, delete even after subscribing to channels.

**Comment by SilvVF** [comment]
<img width="897" alt="Screenshot 2023-08-16 at 3 16 58 AM" src="https://github.com/SilvVF/SupabaseRealtimeChatSwift/assets/98186105/659a11a2-2020-48b4-82ee-258d7e6a19f3">
<img width="1153" alt="Screenshot 2023-08-16 at 3 18 47 AM" src="https://github.com/SilvVF/SupabaseRealtimeChatSwift/assets/98186105/f45dda73-3762-411f-8fa2-052f8d69b5f2">

Tested the app using the simulator and still see messages updated in the app and on supabase. Posting db config for future refrence dont plan to update the app at all.
